chore: fail git-hook on failing step

diff --git a/.git-hooks/commit-msg b/.git-hooks/commit-msg
--- a/.git-hooks/commit-msg
+++ b/.git-hooks/commit-msg
@@ -1,4 +1,7 @@
 #!/bin/bash
 
+# exit on non-zero code
+set -e
+
 echo "[Better-Moodle Commit-Msg]: Runnint commitlint"
 yarn commitlint --edit $1
diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,7 +1,10 @@
 #!/bin/bash
 
-echo "[Better-Moodle Pre-Commit]: Running lint:fix"
-yarn lint:fix
+# exit on non-zero code
+set -e
+
+echo "[Better-Moodle Pre-Commit]: Running lint:check"
+yarn lint:check
 
 echo "[Better-Moodle Pre-Commit]: Running prettier:check"
 yarn prettier:check
